In [1]:
#Réalisé Par : 
#Ismail Iaich , Brahim Anougmar , Wissal Hattab

import numpy as np

def MethodeAffectation(C):
    # Réduction des lignes
    C -= np.min(C, axis=1, keepdims=True)
    # Réduction des colonnes
    C -= np.min(C, axis=0, keepdims=True)
    
    n, m = C.shape
    affectations = []
    
    while len(affectations) < n:
        # Sélection des affectations initiales
        row_indices, col_indices = np.where(C == 0)
        row_covered = set()
        col_covered = set()
        for i, j in zip(row_indices, col_indices):
            if i not in row_covered and j not in col_covered:
                affectations.append((i, j))
                row_covered.add(i)
                col_covered.add(j)
        
        # Si toutes les lignes sont couvertes, sortir de la boucle
        if len(affectations) == n:
            break
        
        # Marquer les lignes et les colonnes
        marked_rows = set([row for row, _ in affectations])
        marked_cols = set([col for _, col in affectations])
        
        # Trouver la plus petite valeur non marquée
        min_unmarked = np.inf
        for i in range(n):
            if i not in marked_rows:
                for j in range(m):
                    if j not in marked_cols:
                        min_unmarked = min(min_unmarked, C[i, j])
        
        # Soustraire la plus petite valeur non marquée des éléments non marqués
        # et l'ajouter aux éléments doublement marqués
        for i in range(n):
            for j in range(m):
                if i in marked_rows and j in marked_cols:
                    C[i, j] += min_unmarked
                elif i not in marked_rows and j not in marked_cols:
                    C[i, j] -= min_unmarked
    
    return affectations

# Exemple d'utilisation
C = np.array([[4, 5, 6],
              [3, 2, 1],
              [6, 5, 4]])

affectations = MethodeAffectation(C)
print("Affectations optimales:", affectations)

import numpy as np
from scipy.optimize import linear_sum_assignment

# Définition de la matrice des coûts
C = np.array([[4, 5, 6],
              [3, 2, 1],
              [6, 5, 4]])

# Utilisation de la fonction linear_sum_assignment pour résoudre le problème d'affectation
# linear_sum_assignment trouve l'association qui minimise la somme des coûts
# L'algorithme utilisé est la méthode hongroise
row_indices, col_indices = linear_sum_assignment(C)

# Affichage des affectations optimales
for i, j in zip(row_indices, col_indices):
    print(f"Agent {i} est affecté à la tâche {j}, coût : {C[i][j]}")

# Calcul du coût total optimal
cout_total_optimal = C[row_indices, col_indices].sum()
print(f"Coût total optimal : {cout_total_optimal}")



Affectations optimales: [(0, 0), (1, 1), (2, 2)]
Agent 0 est affecté à la tâche 0, coût : 4
Agent 1 est affecté à la tâche 2, coût : 1
Agent 2 est affecté à la tâche 1, coût : 5
Coût total optimal : 10


In [2]:
import numpy as np

def MethodeAffectation(C):
    # Création d'une copie de la matrice de coûts
    C_copy = np.copy(C)
    
    # Réduction des lignes
    C_copy -= np.min(C_copy, axis=1, keepdims=True)
    # Réduction des colonnes
    C_copy -= np.min(C_copy, axis=0, keepdims=True)
    
    n, m = C_copy.shape
    affectations = []
    
    while len(affectations) < n:
        # Sélection des affectations initiales
        row_indices, col_indices = np.where(C_copy == 0)
        row_covered = set()
        col_covered = set()
        for i, j in zip(row_indices, col_indices):
            if i not in row_covered and j not in col_covered:
                affectations.append((i, j))
                row_covered.add(i)
                col_covered.add(j)
        
        # Si toutes les lignes sont couvertes, sortir de la boucle
        if len(affectations) == n:
            break
        
        # Marquer les lignes et les colonnes
        marked_rows = set([row for row, _ in affectations])
        marked_cols = set([col for _, col in affectations])
        
        # Trouver la plus petite valeur non marquée
        min_unmarked = np.inf
        for i in range(n):
            if i not in marked_rows:
                for j in range(m):
                    if j not in marked_cols:
                        min_unmarked = min(min_unmarked, C_copy[i, j])
        
        # Soustraire la plus petite valeur non marquée des éléments non marqués
        # et l'ajouter aux éléments doublement marqués
        for i in range(n):
            for j in range(m):
                if i in marked_rows and j in marked_cols:
                    C_copy[i, j] += min_unmarked
                elif i not in marked_rows and j not in marked_cols:
                    C_copy[i, j] -= min_unmarked
    
    # Calcul du coût total des affectations à partir de la matrice initiale
    cout_total = sum(C[affectation] for affectation in affectations)
    
    return affectations, cout_total

# Exemple d'utilisation
C = np.array([[4, 5, 6],
              [3, 2, 1],
              [6, 5, 4]])

affectations, cout_total = MethodeAffectation(C)
print("Affectations optimales:", affectations)
print("Coût total des affectations:", cout_total)


Affectations optimales: [(0, 0), (1, 1), (2, 2)]
Coût total des affectations: 10


In [3]:
import numpy as np

def coin_nord_ouest(offres, demandes, couts):
    lignes, colonnes = len(offres), len(demandes)
    affectations = np.zeros((lignes, colonnes))
    
    i, j = 0, 0
    
    while i < lignes and j < colonnes:
        # Calcul de la quantité à affecter (minimum entre l'offre et la demande)
        quantite_affectee = min(offres[i], demandes[j])
        
        # Affectation de la quantité
        affectations[i][j] = quantite_affectee
        
        # Mise à jour des offres et demandes restantes
        offres[i] -= quantite_affectee
        demandes[j] -= quantite_affectee
        
        # Passage à la prochaine ligne ou colonne si l'offre ou la demande est épuisée
        if offres[i] == 0:
            i += 1
        if demandes[j] == 0:
            j += 1
    
    return affectations

# Exemple d'utilisation
offres = np.array([20, 30, 40])
demandes = np.array([30, 50, 30])
couts = np.array([[5, 8, 7],
                  [7, 12, 10],
                  [8, 6, 4]])

affectations = coin_nord_ouest(offres, demandes, couts)
print("Affectations optimales :\n", affectations)
# Calcul du coût total des affectations
cout_total = np.sum(affectations * couts)
print("Coût total des affectations :", cout_total)



Affectations optimales :
 [[20.  0.  0.]
 [10. 20.  0.]
 [ 0. 30. 10.]]
Coût total des affectations : 630.0


In [4]:
import numpy as np
def trouver_cellule_min(couts, offres, demandes):
    min_cout = np.inf
    i_min, j_min = -1, -1
    
    for i in range(len(offres)):
        for j in range(len(demandes)):
            if offres[i] > 0 and demandes[j] > 0:
                if couts[i][j] < min_cout:
                    min_cout = couts[i][j]
                    i_min, j_min = i, j
    return min_cout, i_min, j_min
def methode_cout_minimum(offres, demandes, couts):
    lignes, colonnes = len(offres), len(demandes)
    affectations = np.zeros((lignes, colonnes))
    while np.any(offres > 0) and np.any(demandes > 0):
        min_cout, i_min, j_min = trouver_cellule_min(couts, offres, demandes)
        if min_cout == np.inf:
            break
        quantite_affectee = min(offres[i_min], demandes[j_min])
        
        affectations[i_min][j_min] = quantite_affectee
        
        offres[i_min] -= quantite_affectee
        demandes[j_min] -= quantite_affectee
    return affectations
# Exemple d'utilisation
offres = np.array([20, 30, 40])
demandes = np.array([30, 50, 30])
couts = np.array([[5, 8, 7],
                  [7, 12, 10],
                  [8, 6, 4]])

affectations = methode_cout_minimum(offres, demandes, couts)
print("Affectations optimales :\n", affectations)

# Calcul du coût total des affectations
cout_total = np.sum(affectations * couts)
print("Coût total des affectations :", cout_total)

Affectations optimales :
 [[20.  0.  0.]
 [10. 20.  0.]
 [ 0. 10. 30.]]
Coût total des affectations : 590.0


In [5]:
import numpy as np

# Données
chauffeurs = {'A': 5, 'B': 4}
livraisons = {'1': {'distance': 10, 'temps': 1},
              '2': {'distance': 15, 'temps': 1.5},
              '3': {'distance': 20, 'temps': 2},
              '4': {'distance': 12, 'temps': 1.2},
              '5': {'distance': 18, 'temps': 1.8}}
cout_kilometre = 0.5
cout_heure = 10

# Calcul des coûts
couts = np.zeros((len(chauffeurs), len(livraisons)))
for i, (chauffeur, capacite) in enumerate(chauffeurs.items()):
    for j, (livraison, details) in enumerate(livraisons.items()):
        couts[i][j] = (details['distance'] * cout_kilometre) + (details['temps'] * cout_heure)

# Résolution du problème
from scipy.optimize import linear_sum_assignment
affectations = linear_sum_assignment(couts)
print("Affectations optimales :\n", affectations)


Affectations optimales :
 (array([0, 1], dtype=int64), array([0, 3], dtype=int64))


In [6]:
# Affectations optimales
chauffeurs_indices, livraisons_indices = affectations

# Planification des livraisons
planification = {}

for i, chauffeur_idx in enumerate(chauffeurs_indices):
    chauffeur = list(chauffeurs.keys())[chauffeur_idx]
    livraison = list(livraisons.keys())[livraisons_indices[i]]
    if livraison not in planification:
        planification[livraison] = [chauffeur]
    else:
        planification[livraison].append(chauffeur)

# Affichage de la planification des livraisons
print("Planification des livraisons :")
for livraison, chauffeurs in planification.items():
    print(f"Livraison {livraison} : Chauffeurs {', '.join(chauffeurs)}")


Planification des livraisons :
Livraison 1 : Chauffeurs A
Livraison 4 : Chauffeurs B


In [7]:
import numpy as np
from scipy.optimize import linear_sum_assignment
# Données
entrepots = {'A': 100, 'B': 150, 'C': 200}
supermarches = {'1': {'A': 80, 'B': 50, 'C': 70},
                '2': {'A': 100, 'B': 120, 'C': 90},
                '3': {'A': 70, 'B': 60, 'C': 80},
                '4': {'A': 60, 'B': 80, 'C': 100},
                '5': {'A': 90, 'B': 70, 'C': 110}}
couts_transport = np.array([[5, 4, 6],
                            [7, 6, 8],
                            [6, 5, 7]])
# Matrices d'offres et de demandes
offres = np.array([entrepots[entrepot] for entrepot in entrepots.keys()])
demandes = np.array([sum(supermarches[supermarche].values()) 
                     for supermarche in supermarches.keys()])
# Résolution du problème d'assignation (transport)
affectations = linear_sum_assignment(couts_transport)
# Planification des expéditions
planification = {}
for i, entrepot_idx in enumerate(affectations[0]):
    supermarche_idx = affectations[1][i]
    entrepot = list(entrepots.keys())[entrepot_idx]
    supermarche = list(supermarches.keys())[supermarche_idx]
    quantites = {produit: supermarches[supermarche][produit] 
                 for produit in supermarches[supermarche].keys()}
    if entrepot not in planification:
        planification[entrepot] = {supermarche: quantites}
    else:
        planification[entrepot][supermarche] = quantites
# Affichage de la planification des expéditions
print("Planification des expéditions :")
for entrepot, expeditions in planification.items():
    for supermarche, quantites in expeditions.items():
        print(f"De {entrepot} à Supermarché {supermarche} : {quantites}")

Planification des expéditions :
De A à Supermarché 2 : {'A': 100, 'B': 120, 'C': 90}
De B à Supermarché 1 : {'A': 80, 'B': 50, 'C': 70}
De C à Supermarché 3 : {'A': 70, 'B': 60, 'C': 80}
